// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package attachment

import (
	"server/app/admin/api/attachment"
)

type ControllerV1 struct{}

func NewV1() attachment.IAttachmentV1 {
	return &ControllerV1{}
}
