// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package generate

import (
	"server/app/admin/api/generate"
)

type ControllerV1 struct{}

func NewV1() generate.IGenerateV1 {
	return &ControllerV1{}
}
