// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/app/admin/internal/dao/internal"
)

// codeGenRecordDao is the data access object for the table code_gen_record.
// You can define custom methods on it to extend its functionality as needed.
type codeGenRecordDao struct {
	*internal.CodeGenRecordDao
}

var (
	// CodeGenRecord is a globally accessible object for table code_gen_record operations.
	CodeGenRecord = codeGenRecordDao{internal.NewCodeGenRecordDao()}
)

// Add your custom methods and functionality below.
