// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/app/admin/internal/dao/internal"
)

// dictDao is the data access object for the table dict.
// You can define custom methods on it to extend its functionality as needed.
type dictDao struct {
	*internal.DictDao
}

var (
	// Dict is a globally accessible object for table dict operations.
	Dict = dictDao{internal.NewDictDao()}
)

// Add your custom methods and functionality below.
