// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/app/admin/internal/dao/internal"
)

// testDao is the data access object for the table test.
// You can define custom methods on it to extend its functionality as needed.
type testDao struct {
	*internal.TestDao
}

var (
	// Test is a globally accessible object for table test operations.
	Test = testDao{internal.NewTestDao()}
)

// Add your custom methods and functionality below.
