// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package department

import (
	"server/app/admin/api/department"
)

type ControllerV1 struct{}

func NewV1() department.IDepartmentV1 {
	return &ControllerV1{}
}
